### PR TITLE
better shader with sky/ground light, along with half lambert

### PR DESCRIPTION
**Pull request by qiankanglai**
Compared with
qq 20170924224918
to
qq 20170924224736

I added Sky/Ground Light along with Half Lambert. Color was removed since it may present special use with custom shader, which is confusing sometime.

TODO: recalculate normal; SSAO for better view

### CODE REVIEW

**Comment by qiankanglai** [comment]
recalculate normal DONE: some mesh may come with wrong normal (or hand modified...)
qq 20170925000321
recalculate version:
qq 20170925000940

Also this step only affects previewing, not exporting

**Comment by Perfare** [comment]
I'm not sure remove color whether it's a good idea, some file like this one
https://mega.nz/#!TA1UiaJZ!odCyq-lbyFKtM9pYQxNb37n0Idf-8MxU-7qffduMBeM
Including colors will make the preview better

**Comment by qiankanglai** [comment]
what about more preview types:
- default mode (as I implemented)
- normal mode
- color mode
- wire frame

**Comment by qiankanglai** [comment]
more modes supported!
Ctrl+S: switch shade mode (Lambert vs. VertexColor)

Ctrl+W: switch wireframe mode

Ctrl+N: whether to use recalculated normal


ps. This has some conflicts with my another PR, and I'll fix it later after one has merged

**Comment by Perfare** [comment]
OK, I'll merge this first.

**Pull request merged**
