### PR TITLE
Fix invalid filename bug and add a option

### PR DESCRIPTION
**Pull request by xykong**
Fix invalid filename when export in windows.
Add option of exportSameNameMesh.

### CODE REVIEW

**Comment by Perfare** [comment]
Thank you for fix bug, but I don't know what "exportSameNameMesh" is for

**Comment by Tosyk** [comment]
I suppose he means that models (.FBX) came out off UnityStudio with the current date and time name however it has its own name in the asset.
For ex.: I open UnityStudio and find model called 'mesh_BigThoughArmored_V2' and when I export it the Studio suggest name for .FBX like this: '2017-07-15-11-03-28.FBX'.
So it would be very usefull to use original model name for .FBX and produce file 'mesh_BigThoughArmored_V2.fbx'.

**Comment by xykong** [comment]
Yes, @Tosyk is right.
The original model name plus with time stamp will generate many same models with different names.
This often happens when a model used many times in on scene or in many scenes.

And the option name should be more clearly. "exportSameNameMesh" is not good enough.
May be exportMeshOnce? exportMeshWithoutTimeStamp? 
I'm not good at naming...

**Comment by Perfare** [comment]
@xykong But your code will appear if different object have the same name, will export only one file. Before export we don't know which files are useful, so I don't think this option makes any sense

**Pull request closed without merging**
