### PR TITLE
Added ExportMesh support --utilizing a modified ManagedFbx

### PR DESCRIPTION
**Pull request by ordigdug**
https://github.com/ordigdug/ManagedFBX (.NET wrapper for Autodesk's FBX SDK, written in C++/CLI.)
Currently exports Mesh in 3 file types (.fbx, .dae & .obj/.mtl). 
Mesh attributes extracted: Vertices, Normals, Indices, & VertexColors.

### CODE REVIEW

**Comment by Perfare** [comment]
This is great!

**Comment by Perfare** [comment]
I find ManagedFbx.dll Is a 64 bit version, If UnityStudio run on 32 bit computer need to recompile the version of the 32bit

**Comment by ordigdug** [comment]
I'm kinda new at this, is there a way to compile both 32 & 64 bit versions of the .dll?

**Comment by ordigdug** [comment]
I am unable to compile it in 32bit with my current VS2015 setup. Any ideas?
Get C1083 errors: 
- Cannot open source file: '_ITERATOR_DEBUG_LEVEL': No such / FILE: c1xx
- Cannot open source file: '=': No such file or directory
- Cannot open source file: '0': No such file or directory

**Comment by ordigdug** [comment]
I'm currently working through issues on compiling in 32bit.

**Comment by ordigdug** [comment]
I finally got ManagedFbx.dll to compile as 32bit.

**Comment by Perfare** [comment]
@ordigdug great, can you upload the file? I'll add it to the source code

**Pull request merged**
